controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controller_upper:
      type: chaining_controller/EffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controller_upper:
  ros__parameters:
    joints:
      - slider_to_cart
